### ISSUE TITLE
[PE-D] `colourt` not working as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-2/tp#171]
**Steps to reproduce:**
1. `colourt n/friends c/255 255 255`

**Expected:**
Tag colour of friends to be changed to white

**Actual:**
status msg: Tag colour changed: friends but tag colour is not changed

![Screenshot 2021-10-29 at 4.53.22 PM.png](https://raw.githubusercontent.com/wanninglim/ped/main/files/06dba528-2f9a-4085-a89c-d62113f8edb0.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: wanninglim/ped#11

**Comment by justintanyf** [comment]
Already fixed but not in the release jar :>
