### ISSUE TITLE
[PE-D] editc command format is different in App and in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-2/tp#175]
editc command in UG contains extra 'cid' field, which is unused in app. Standardisation would make it clearer.

App:
![editc ap.png](https://raw.githubusercontent.com/juliussneezer04/ped/main/files/9a6ad0fe-800b-494c-a188-a1afe9cce974.png)

UG:

![editc ug.png](https://raw.githubusercontent.com/juliussneezer04/ped/main/files/20bc2457-a30e-4dcd-9dbc-a9ab255f2c8c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: juliussneezer04/ped#14

**Comment by jovyntls** [comment]
closed by #172
