### ISSUE TITLE
[PE-D] Frequency field in reminder commands not explained

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-2/tp#200]
The frequency field of reminder commands is not explained, especially since it is slight different (requiring number and d or w or y)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: juliussneezer04/ped#38

**Comment by jovyntls** [comment]
I added a table before the commands explaining the frequency field, but maybe can add additional description under its command too
