### ISSUE TITLE
Displayed items should reset after an add command

### ISSUE THREAD

**Issue by jovyntls** [AY2122S1-CS2103-T14-2/tp#216]
e.g. After I do a `findc NUSSO` command, I may run an `addr USC` command to add a reminder to USC. After I execute this command, I have all the NUSSO-related entries listed, along with a random USC reminder.
After the command is executed, persons, CCAs and reminders lists should all refresh

**Comment by okyntary** [comment]
After Monday's discussion, @weiquu mentioned that he managed this refreshing issue. (Weiqing, If I remembered wrongly please correct me and reopen this issue.)
