### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by jovyntls** [AY2122S1-CS2103-T14-2/tp#236]
Make sure you change both the `.puml` and the `.png`

- [x] Change UML diagram from `delete` to `deletep` under [this section](https://github.com/AY2122S1-CS2103-T14-2/tp/blob/master/docs/DeveloperGuide.md#architecture)
- [x] Add Cca and Reminder to the UML diagram under [this section](https://github.com/AY2122S1-CS2103-T14-2/tp/blob/master/docs/DeveloperGuide.md#ui-component) - currently only has Person
- [x] Change the [second UML diagram under this section](https://github.com/AY2122S1-CS2103-T14-2/tp/blob/master/docs/DeveloperGuide.md#logic-component) to the right class names and command syntax (PersonDeleteCommand instead of DeleteCommand) 
- [x] Update the Model UML diagram [here](https://github.com/AY2122S1-CS2103-T14-2/tp/blob/master/docs/DeveloperGuide.md#model-component) - if too messy, can exclude the Person/Cca/Reminder attributes and add a note that these attributes are excluded 
- [x] Update the storage UML diagram [here](https://github.com/AY2122S1-CS2103-T14-2/tp/blob/master/docs/DeveloperGuide.md#storage-component)

**Comment by jovyntls** [comment]
I think we should change anything that isn't updated to our current app and isn't accurate to our current architecture
everything else should be fine

**Comment by okyntary** [comment]
Yeah that's what I meant, just that there's probably stuff beyond your checklist that we also have to change.

**Comment by jovyntls** [comment]
I think an exhaustive checklist is unfeasible - if anyone sees anything just change
